"""Change economic calendar event date to datetime

Revision ID: 04608cf2f87e
Revises: 42a68bdd9bbd
Create Date: 2026-01-15 21:44:43.554893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04608cf2f87e'
down_revision = '42a68bdd9bbd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dividendcalendarevent', 'date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using = 'date::date')
    op.alter_column('economiccalendarevent', 'date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('economiccalendarevent', 'date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('dividendcalendarevent', 'date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
