"""Remove country and period from EconomicIndicator

Revision ID: 12282951cc02
Revises: 04608cf2f87e
Create Date: 2026-01-15 21:31:57.188175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12282951cc02'
down_revision = '04608cf2f87e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove duplicate records before creating new unique index (keep one per name/date)
    op.execute("""
        DELETE FROM economicindicator
        WHERE id NOT IN (
            SELECT MIN(id)
            FROM economicindicator
            GROUP BY name, date
        )
    """)
    op.drop_index('idx_econ_indicator_name_date_country', table_name='economicindicator')
    op.drop_index('ix_economicindicator_country', table_name='economicindicator')
    op.create_index('idx_econ_indicator_name_date', 'economicindicator', ['name', 'date'], unique=True)
    op.drop_column('economicindicator', 'country')
    op.drop_column('economicindicator', 'period')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('economicindicator', sa.Column('period', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('economicindicator', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index('idx_econ_indicator_name_date', table_name='economicindicator')
    op.create_index('ix_economicindicator_country', 'economicindicator', ['country'], unique=False)
    op.create_index('idx_econ_indicator_name_date_country', 'economicindicator', ['name', 'date', 'country'], unique=True)
    # ### end Alembic commands ###
