"""Create news models

Revision ID: 42a68bdd9bbd
Revises: 898485f13588
Create Date: 2026-01-11 15:59:55.302349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42a68bdd9bbd'
down_revision = '898485f13588'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fmparticle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tickers', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fmparticle_link_date', 'fmparticle', ['link', 'date'], unique=True)
    op.create_index('idx_fmparticle_tickers', 'fmparticle', ['tickers'], unique=False)
    op.create_index(op.f('ix_fmparticle_date'), 'fmparticle', ['date'], unique=False)
    op.create_index(op.f('ix_fmparticle_id'), 'fmparticle', ['id'], unique=False)
    op.create_table('generalnews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('published_date', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_generalnews_url', 'generalnews', ['url'], unique=True)
    op.create_index(op.f('ix_generalnews_id'), 'generalnews', ['id'], unique=False)
    op.create_index(op.f('ix_generalnews_published_date'), 'generalnews', ['published_date'], unique=False)
    op.create_index(op.f('ix_generalnews_symbol'), 'generalnews', ['symbol'], unique=False)
    op.create_table('stocknews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=False),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stocknews_symbol_date', 'stocknews', ['symbol', 'published_date'], unique=False)
    op.create_index('idx_stocknews_url', 'stocknews', ['symbol', 'url'], unique=True)
    op.create_index(op.f('ix_stocknews_id'), 'stocknews', ['id'], unique=False)
    op.create_index(op.f('ix_stocknews_published_date'), 'stocknews', ['published_date'], unique=False)
    op.create_index(op.f('ix_stocknews_symbol'), 'stocknews', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocknews_symbol'), table_name='stocknews')
    op.drop_index(op.f('ix_stocknews_published_date'), table_name='stocknews')
    op.drop_index(op.f('ix_stocknews_id'), table_name='stocknews')
    op.drop_index('idx_stocknews_url', table_name='stocknews')
    op.drop_index('idx_stocknews_symbol_date', table_name='stocknews')
    op.drop_table('stocknews')
    op.drop_index(op.f('ix_generalnews_symbol'), table_name='generalnews')
    op.drop_index(op.f('ix_generalnews_published_date'), table_name='generalnews')
    op.drop_index(op.f('ix_generalnews_id'), table_name='generalnews')
    op.drop_index('idx_generalnews_url', table_name='generalnews')
    op.drop_table('generalnews')
    op.drop_index(op.f('ix_fmparticle_id'), table_name='fmparticle')
    op.drop_index(op.f('ix_fmparticle_date'), table_name='fmparticle')
    op.drop_index('idx_fmparticle_tickers', table_name='fmparticle')
    op.drop_index('idx_fmparticle_link_date', table_name='fmparticle')
    op.drop_table('fmparticle')
    # ### end Alembic commands ###
