"""FMP models

Revision ID: 43a939f4a0b6
Revises: 4a2498c2fd9e
Create Date: 2026-01-03 16:42:00.247630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '43a939f4a0b6'
down_revision = '4a2498c2fd9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activestock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('changes_percentage', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_active_date_symbol', 'activestock', ['date', 'symbol'], unique=False)
    op.create_index(op.f('ix_activestock_date'), 'activestock', ['date'], unique=False)
    op.create_index(op.f('ix_activestock_id'), 'activestock', ['id'], unique=False)
    op.create_index(op.f('ix_activestock_symbol'), 'activestock', ['symbol'], unique=False)
    op.create_table('balancesheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('reported_currency', sa.String(), nullable=True),
    sa.Column('cik', sa.String(), nullable=True),
    sa.Column('filling_date', sa.String(), nullable=True),
    sa.Column('accepted_date', sa.String(), nullable=True),
    sa.Column('calendar_year', sa.String(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('cash_and_cash_equivalents', sa.Float(), nullable=True),
    sa.Column('short_term_investments', sa.Float(), nullable=True),
    sa.Column('cash_and_short_term_investments', sa.Float(), nullable=True),
    sa.Column('net_receivables', sa.Float(), nullable=True),
    sa.Column('inventory', sa.Float(), nullable=True),
    sa.Column('other_current_assets', sa.Float(), nullable=True),
    sa.Column('total_current_assets', sa.Float(), nullable=True),
    sa.Column('property_plant_equipment_net', sa.Float(), nullable=True),
    sa.Column('goodwill', sa.Float(), nullable=True),
    sa.Column('intangible_assets', sa.Float(), nullable=True),
    sa.Column('goodwill_and_intangible_assets', sa.Float(), nullable=True),
    sa.Column('long_term_investments', sa.Float(), nullable=True),
    sa.Column('tax_assets', sa.Float(), nullable=True),
    sa.Column('other_non_current_assets', sa.Float(), nullable=True),
    sa.Column('total_non_current_assets', sa.Float(), nullable=True),
    sa.Column('other_assets', sa.Float(), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('account_payables', sa.Float(), nullable=True),
    sa.Column('short_term_debt', sa.Float(), nullable=True),
    sa.Column('tax_payables', sa.Float(), nullable=True),
    sa.Column('deferred_revenue', sa.Float(), nullable=True),
    sa.Column('other_current_liabilities', sa.Float(), nullable=True),
    sa.Column('total_current_liabilities', sa.Float(), nullable=True),
    sa.Column('long_term_debt', sa.Float(), nullable=True),
    sa.Column('deferred_revenue_non_current', sa.Float(), nullable=True),
    sa.Column('deferred_tax_liabilities_non_current', sa.Float(), nullable=True),
    sa.Column('other_non_current_liabilities', sa.Float(), nullable=True),
    sa.Column('total_non_current_liabilities', sa.Float(), nullable=True),
    sa.Column('other_liabilities', sa.Float(), nullable=True),
    sa.Column('capital_lease_obligations', sa.Float(), nullable=True),
    sa.Column('total_liabilities', sa.Float(), nullable=True),
    sa.Column('preferred_stock', sa.Float(), nullable=True),
    sa.Column('common_stock', sa.Float(), nullable=True),
    sa.Column('retained_earnings', sa.Float(), nullable=True),
    sa.Column('accumulated_other_comprehensive_income_loss', sa.Float(), nullable=True),
    sa.Column('other_total_stockholders_equity', sa.Float(), nullable=True),
    sa.Column('total_stockholders_equity', sa.Float(), nullable=True),
    sa.Column('total_equity', sa.Float(), nullable=True),
    sa.Column('total_liabilities_and_stockholders_equity', sa.Float(), nullable=True),
    sa.Column('minority_interest', sa.Float(), nullable=True),
    sa.Column('total_liabilities_and_total_equity', sa.Float(), nullable=True),
    sa.Column('total_investments', sa.Float(), nullable=True),
    sa.Column('total_debt', sa.Float(), nullable=True),
    sa.Column('net_debt', sa.Float(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('final_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_balance_sheet_symbol_date', 'balancesheet', ['symbol', 'date'], unique=True)
    op.create_index('idx_balance_sheet_symbol_period', 'balancesheet', ['symbol', 'calendar_year', 'period'], unique=False)
    op.create_index(op.f('ix_balancesheet_calendar_year'), 'balancesheet', ['calendar_year'], unique=False)
    op.create_index(op.f('ix_balancesheet_date'), 'balancesheet', ['date'], unique=False)
    op.create_index(op.f('ix_balancesheet_id'), 'balancesheet', ['id'], unique=False)
    op.create_index(op.f('ix_balancesheet_period'), 'balancesheet', ['period'], unique=False)
    op.create_index(op.f('ix_balancesheet_symbol'), 'balancesheet', ['symbol'], unique=False)
    op.create_table('cashflowstatement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('reported_currency', sa.String(), nullable=True),
    sa.Column('cik', sa.String(), nullable=True),
    sa.Column('filling_date', sa.String(), nullable=True),
    sa.Column('accepted_date', sa.String(), nullable=True),
    sa.Column('calendar_year', sa.String(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('depreciation_and_amortization', sa.Float(), nullable=True),
    sa.Column('deferred_income_tax', sa.Float(), nullable=True),
    sa.Column('stock_based_compensation', sa.Float(), nullable=True),
    sa.Column('change_in_working_capital', sa.Float(), nullable=True),
    sa.Column('accounts_receivables', sa.Float(), nullable=True),
    sa.Column('inventory', sa.Float(), nullable=True),
    sa.Column('accounts_payables', sa.Float(), nullable=True),
    sa.Column('other_working_capital', sa.Float(), nullable=True),
    sa.Column('other_non_cash_items', sa.Float(), nullable=True),
    sa.Column('net_cash_provided_by_operating_activities', sa.Float(), nullable=True),
    sa.Column('investments_in_property_plant_and_equipment', sa.Float(), nullable=True),
    sa.Column('acquisitions_net', sa.Float(), nullable=True),
    sa.Column('purchases_of_investments', sa.Float(), nullable=True),
    sa.Column('sales_maturities_of_investments', sa.Float(), nullable=True),
    sa.Column('other_investing_activities', sa.Float(), nullable=True),
    sa.Column('net_cash_used_for_investing_activities', sa.Float(), nullable=True),
    sa.Column('debt_repayment', sa.Float(), nullable=True),
    sa.Column('common_stock_issued', sa.Float(), nullable=True),
    sa.Column('common_stock_repurchased', sa.Float(), nullable=True),
    sa.Column('dividends_paid', sa.Float(), nullable=True),
    sa.Column('other_financing_activities', sa.Float(), nullable=True),
    sa.Column('net_cash_used_provided_by_financing_activities', sa.Float(), nullable=True),
    sa.Column('effect_of_forex_changes_on_cash', sa.Float(), nullable=True),
    sa.Column('net_change_in_cash', sa.Float(), nullable=True),
    sa.Column('cash_at_end_of_period', sa.Float(), nullable=True),
    sa.Column('cash_at_beginning_of_period', sa.Float(), nullable=True),
    sa.Column('operating_cash_flow', sa.Float(), nullable=True),
    sa.Column('capital_expenditure', sa.Float(), nullable=True),
    sa.Column('free_cash_flow', sa.Float(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('final_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cash_flow_symbol_date', 'cashflowstatement', ['symbol', 'date'], unique=True)
    op.create_index('idx_cash_flow_symbol_period', 'cashflowstatement', ['symbol', 'calendar_year', 'period'], unique=False)
    op.create_index(op.f('ix_cashflowstatement_calendar_year'), 'cashflowstatement', ['calendar_year'], unique=False)
    op.create_index(op.f('ix_cashflowstatement_date'), 'cashflowstatement', ['date'], unique=False)
    op.create_index(op.f('ix_cashflowstatement_id'), 'cashflowstatement', ['id'], unique=False)
    op.create_index(op.f('ix_cashflowstatement_period'), 'cashflowstatement', ['period'], unique=False)
    op.create_index(op.f('ix_cashflowstatement_symbol'), 'cashflowstatement', ['symbol'], unique=False)
    op.create_table('companyprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('vol_avg', sa.Integer(), nullable=True),
    sa.Column('mkt_cap', sa.Integer(), nullable=True),
    sa.Column('last_div', sa.Float(), nullable=True),
    sa.Column('range', sa.String(), nullable=True),
    sa.Column('changes', sa.Float(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('cik', sa.String(), nullable=True),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('cusip', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('exchange_short_name', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('ceo', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('full_time_employees', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip', sa.String(), nullable=True),
    sa.Column('dcf_diff', sa.Float(), nullable=True),
    sa.Column('dcf', sa.Float(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('ipo_date', sa.String(), nullable=True),
    sa.Column('default_image', sa.Boolean(), nullable=True),
    sa.Column('is_etf', sa.Boolean(), nullable=True),
    sa.Column('is_actively_trading', sa.Boolean(), nullable=True),
    sa.Column('is_adr', sa.Boolean(), nullable=True),
    sa.Column('is_fund', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_company_country_exchange', 'companyprofile', ['country', 'exchange'], unique=False)
    op.create_index('idx_company_sector_industry', 'companyprofile', ['sector', 'industry'], unique=False)
    op.create_index(op.f('ix_companyprofile_cik'), 'companyprofile', ['cik'], unique=False)
    op.create_index(op.f('ix_companyprofile_country'), 'companyprofile', ['country'], unique=False)
    op.create_index(op.f('ix_companyprofile_id'), 'companyprofile', ['id'], unique=False)
    op.create_index(op.f('ix_companyprofile_industry'), 'companyprofile', ['industry'], unique=False)
    op.create_index(op.f('ix_companyprofile_sector'), 'companyprofile', ['sector'], unique=False)
    op.create_index(op.f('ix_companyprofile_symbol'), 'companyprofile', ['symbol'], unique=True)
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country')
    )
    op.create_index(op.f('ix_country_id'), 'country', ['id'], unique=False)
    op.create_table('delistedcompany',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('ipo_date', sa.String(), nullable=True),
    sa.Column('delisted_date', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delistedcompany_delisted_date'), 'delistedcompany', ['delisted_date'], unique=False)
    op.create_index(op.f('ix_delistedcompany_id'), 'delistedcompany', ['id'], unique=False)
    op.create_index(op.f('ix_delistedcompany_symbol'), 'delistedcompany', ['symbol'], unique=True)
    op.create_table('dividend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('adj_dividend', sa.Float(), nullable=True),
    sa.Column('dividend', sa.Float(), nullable=True),
    sa.Column('record_date', sa.String(), nullable=True),
    sa.Column('payment_date', sa.String(), nullable=True),
    sa.Column('declaration_date', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dividend_symbol_date', 'dividend', ['symbol', 'date'], unique=True)
    op.create_index(op.f('ix_dividend_date'), 'dividend', ['date'], unique=False)
    op.create_index(op.f('ix_dividend_id'), 'dividend', ['id'], unique=False)
    op.create_index(op.f('ix_dividend_symbol'), 'dividend', ['symbol'], unique=False)
    op.create_table('dividendcalendarevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('adj_dividend', sa.Float(), nullable=True),
    sa.Column('dividend', sa.Float(), nullable=True),
    sa.Column('record_date', sa.String(), nullable=True),
    sa.Column('payment_date', sa.String(), nullable=True),
    sa.Column('declaration_date', sa.String(), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_div_calendar_symbol_date', 'dividendcalendarevent', ['symbol', 'date'], unique=False)
    op.create_index(op.f('ix_dividendcalendarevent_date'), 'dividendcalendarevent', ['date'], unique=False)
    op.create_index(op.f('ix_dividendcalendarevent_id'), 'dividendcalendarevent', ['id'], unique=False)
    op.create_index(op.f('ix_dividendcalendarevent_symbol'), 'dividendcalendarevent', ['symbol'], unique=False)
    op.create_table('earningscalendarevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('eps_estimated', sa.Float(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('revenue_estimated', sa.Float(), nullable=True),
    sa.Column('fiscal_date_ending', sa.String(), nullable=True),
    sa.Column('updated_from_date', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_earnings_cal_symbol_date', 'earningscalendarevent', ['symbol', 'date'], unique=False)
    op.create_index(op.f('ix_earningscalendarevent_date'), 'earningscalendarevent', ['date'], unique=False)
    op.create_index(op.f('ix_earningscalendarevent_id'), 'earningscalendarevent', ['id'], unique=False)
    op.create_index(op.f('ix_earningscalendarevent_symbol'), 'earningscalendarevent', ['symbol'], unique=False)
    op.create_table('earningsreport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('eps_estimated', sa.Float(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('revenue_estimated', sa.Float(), nullable=True),
    sa.Column('fiscal_date_ending', sa.String(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_earnings_symbol_date', 'earningsreport', ['symbol', 'date'], unique=True)
    op.create_index('idx_earnings_symbol_period', 'earningsreport', ['symbol', 'period'], unique=False)
    op.create_index(op.f('ix_earningsreport_date'), 'earningsreport', ['date'], unique=False)
    op.create_index(op.f('ix_earningsreport_id'), 'earningsreport', ['id'], unique=False)
    op.create_index(op.f('ix_earningsreport_period'), 'earningsreport', ['period'], unique=False)
    op.create_index(op.f('ix_earningsreport_symbol'), 'earningsreport', ['symbol'], unique=False)
    op.create_table('economiccalendarevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('event', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('previous', sa.Float(), nullable=True),
    sa.Column('estimate', sa.Float(), nullable=True),
    sa.Column('actual', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('change_percentage', sa.Float(), nullable=True),
    sa.Column('impact', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_econ_cal_date_country', 'economiccalendarevent', ['date', 'country'], unique=False)
    op.create_index('idx_econ_cal_event', 'economiccalendarevent', ['event'], unique=False)
    op.create_index(op.f('ix_economiccalendarevent_country'), 'economiccalendarevent', ['country'], unique=False)
    op.create_index(op.f('ix_economiccalendarevent_date'), 'economiccalendarevent', ['date'], unique=False)
    op.create_index(op.f('ix_economiccalendarevent_event'), 'economiccalendarevent', ['event'], unique=False)
    op.create_index(op.f('ix_economiccalendarevent_id'), 'economiccalendarevent', ['id'], unique=False)
    op.create_table('economicindicator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_econ_indicator_country_name', 'economicindicator', ['country', 'name'], unique=False)
    op.create_index('idx_econ_indicator_name_date', 'economicindicator', ['name', 'date'], unique=False)
    op.create_index(op.f('ix_economicindicator_country'), 'economicindicator', ['country'], unique=False)
    op.create_index(op.f('ix_economicindicator_date'), 'economicindicator', ['date'], unique=False)
    op.create_index(op.f('ix_economicindicator_id'), 'economicindicator', ['id'], unique=False)
    op.create_index(op.f('ix_economicindicator_name'), 'economicindicator', ['name'], unique=False)
    op.create_table('employeecount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('cik', sa.String(), nullable=True),
    sa.Column('acceptance_time', sa.String(), nullable=True),
    sa.Column('period_of_report', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('form_type', sa.String(), nullable=True),
    sa.Column('filing_date', sa.String(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_employee_symbol_date', 'employeecount', ['symbol', 'filing_date'], unique=False)
    op.create_index(op.f('ix_employeecount_filing_date'), 'employeecount', ['filing_date'], unique=False)
    op.create_index(op.f('ix_employeecount_id'), 'employeecount', ['id'], unique=False)
    op.create_index(op.f('ix_employeecount_symbol'), 'employeecount', ['symbol'], unique=False)
    op.create_table('exchange',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_exchange_country'), 'exchange', ['country'], unique=False)
    op.create_index(op.f('ix_exchange_id'), 'exchange', ['id'], unique=False)
    op.create_table('executive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('pay', sa.Float(), nullable=True),
    sa.Column('currency_pay', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('year_born', sa.Integer(), nullable=True),
    sa.Column('title_since', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_executive_symbol_name', 'executive', ['symbol', 'name'], unique=False)
    op.create_index(op.f('ix_executive_id'), 'executive', ['id'], unique=False)
    op.create_index(op.f('ix_executive_symbol'), 'executive', ['symbol'], unique=False)
    op.create_table('historicalprice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('unadjusted_volume', sa.BigInteger(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('change_percent', sa.Float(), nullable=True),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('change_over_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_historical_price_symbol_date', 'historicalprice', ['symbol', 'date'], unique=True)
    op.create_index(op.f('ix_historicalprice_date'), 'historicalprice', ['date'], unique=False)
    op.create_index(op.f('ix_historicalprice_id'), 'historicalprice', ['id'], unique=False)
    op.create_index(op.f('ix_historicalprice_symbol'), 'historicalprice', ['symbol'], unique=False)
    op.create_table('incomestatement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('reported_currency', sa.String(), nullable=True),
    sa.Column('cik', sa.String(), nullable=True),
    sa.Column('filling_date', sa.String(), nullable=True),
    sa.Column('accepted_date', sa.String(), nullable=True),
    sa.Column('calendar_year', sa.String(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('cost_of_revenue', sa.Float(), nullable=True),
    sa.Column('gross_profit', sa.Float(), nullable=True),
    sa.Column('gross_profit_ratio', sa.Float(), nullable=True),
    sa.Column('research_and_development_expenses', sa.Float(), nullable=True),
    sa.Column('general_and_administrative_expenses', sa.Float(), nullable=True),
    sa.Column('selling_and_marketing_expenses', sa.Float(), nullable=True),
    sa.Column('selling_general_and_administrative_expenses', sa.Float(), nullable=True),
    sa.Column('other_expenses', sa.Float(), nullable=True),
    sa.Column('operating_expenses', sa.Float(), nullable=True),
    sa.Column('cost_and_expenses', sa.Float(), nullable=True),
    sa.Column('interest_income', sa.Float(), nullable=True),
    sa.Column('interest_expense', sa.Float(), nullable=True),
    sa.Column('depreciation_and_amortization', sa.Float(), nullable=True),
    sa.Column('ebitda', sa.Float(), nullable=True),
    sa.Column('ebitda_ratio', sa.Float(), nullable=True),
    sa.Column('operating_income', sa.Float(), nullable=True),
    sa.Column('operating_income_ratio', sa.Float(), nullable=True),
    sa.Column('total_other_income_expenses_net', sa.Float(), nullable=True),
    sa.Column('income_before_tax', sa.Float(), nullable=True),
    sa.Column('income_before_tax_ratio', sa.Float(), nullable=True),
    sa.Column('income_tax_expense', sa.Float(), nullable=True),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('net_income_ratio', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('eps_diluted', sa.Float(), nullable=True),
    sa.Column('weighted_average_shs_out', sa.Float(), nullable=True),
    sa.Column('weighted_average_shs_out_dil', sa.Float(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('final_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_income_stmt_symbol_date', 'incomestatement', ['symbol', 'date'], unique=True)
    op.create_index('idx_income_stmt_symbol_period', 'incomestatement', ['symbol', 'calendar_year', 'period'], unique=False)
    op.create_index(op.f('ix_incomestatement_calendar_year'), 'incomestatement', ['calendar_year'], unique=False)
    op.create_index(op.f('ix_incomestatement_date'), 'incomestatement', ['date'], unique=False)
    op.create_index(op.f('ix_incomestatement_id'), 'incomestatement', ['id'], unique=False)
    op.create_index(op.f('ix_incomestatement_period'), 'incomestatement', ['period'], unique=False)
    op.create_index(op.f('ix_incomestatement_symbol'), 'incomestatement', ['symbol'], unique=False)
    op.create_table('industry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('industry')
    )
    op.create_index(op.f('ix_industry_id'), 'industry', ['id'], unique=False)
    op.create_table('industrype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('pe', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_industry_pe_industry_date', 'industrype', ['industry', 'date'], unique=True)
    op.create_index(op.f('ix_industrype_date'), 'industrype', ['date'], unique=False)
    op.create_index(op.f('ix_industrype_id'), 'industrype', ['id'], unique=False)
    op.create_index(op.f('ix_industrype_industry'), 'industrype', ['industry'], unique=False)
    op.create_table('industryperformance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('average_change', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_industry_perf_industry_date', 'industryperformance', ['industry', 'date'], unique=True)
    op.create_index(op.f('ix_industryperformance_date'), 'industryperformance', ['date'], unique=False)
    op.create_index(op.f('ix_industryperformance_id'), 'industryperformance', ['id'], unique=False)
    op.create_index(op.f('ix_industryperformance_industry'), 'industryperformance', ['industry'], unique=False)
    op.create_table('intradayprice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_intraday_price_symbol_date', 'intradayprice', ['symbol', 'date'], unique=True)
    op.create_index(op.f('ix_intradayprice_date'), 'intradayprice', ['date'], unique=False)
    op.create_index(op.f('ix_intradayprice_id'), 'intradayprice', ['id'], unique=False)
    op.create_index(op.f('ix_intradayprice_symbol'), 'intradayprice', ['symbol'], unique=False)
    op.create_table('marketcapitalization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('market_cap', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_market_cap_symbol_date', 'marketcapitalization', ['symbol', 'date'], unique=True)
    op.create_index(op.f('ix_marketcapitalization_date'), 'marketcapitalization', ['date'], unique=False)
    op.create_index(op.f('ix_marketcapitalization_id'), 'marketcapitalization', ['id'], unique=False)
    op.create_index(op.f('ix_marketcapitalization_symbol'), 'marketcapitalization', ['symbol'], unique=False)
    op.create_table('marketriskpremium',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('continent', sa.String(), nullable=True),
    sa.Column('total_equity_risk_premium', sa.Float(), nullable=True),
    sa.Column('country_risk_premium', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country')
    )
    op.create_index(op.f('ix_marketriskpremium_continent'), 'marketriskpremium', ['continent'], unique=False)
    op.create_index(op.f('ix_marketriskpremium_id'), 'marketriskpremium', ['id'], unique=False)
    op.create_table('quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('changes_percentage', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('day_low', sa.Float(), nullable=True),
    sa.Column('day_high', sa.Float(), nullable=True),
    sa.Column('year_high', sa.Float(), nullable=True),
    sa.Column('year_low', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('price_avg_50', sa.Float(), nullable=True),
    sa.Column('price_avg_200', sa.Float(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('avg_volume', sa.Float(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('previous_close', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('pe', sa.Float(), nullable=True),
    sa.Column('earnings_announcement', sa.String(), nullable=True),
    sa.Column('shares_outstanding', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quote_symbol_timestamp', 'quote', ['symbol', 'timestamp'], unique=False)
    op.create_index(op.f('ix_quote_id'), 'quote', ['id'], unique=False)
    op.create_index(op.f('ix_quote_symbol'), 'quote', ['symbol'], unique=False)
    op.create_table('secfiling',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('cik', sa.String(), nullable=True),
    sa.Column('accepted_date', sa.String(), nullable=True),
    sa.Column('filing_date', sa.String(), nullable=False),
    sa.Column('form_type', sa.String(), nullable=True),
    sa.Column('has_financials', sa.Boolean(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('final_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sec_filing_cik_date', 'secfiling', ['cik', 'filing_date'], unique=False)
    op.create_index('idx_sec_filing_form_type', 'secfiling', ['form_type'], unique=False)
    op.create_index('idx_sec_filing_symbol_date', 'secfiling', ['symbol', 'filing_date'], unique=False)
    op.create_index(op.f('ix_secfiling_cik'), 'secfiling', ['cik'], unique=False)
    op.create_index(op.f('ix_secfiling_filing_date'), 'secfiling', ['filing_date'], unique=False)
    op.create_index(op.f('ix_secfiling_form_type'), 'secfiling', ['form_type'], unique=False)
    op.create_index(op.f('ix_secfiling_id'), 'secfiling', ['id'], unique=False)
    op.create_index(op.f('ix_secfiling_symbol'), 'secfiling', ['symbol'], unique=False)
    op.create_table('sector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sector')
    )
    op.create_index(op.f('ix_sector_id'), 'sector', ['id'], unique=False)
    op.create_table('sectorpe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('pe', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sector_pe_sector_date', 'sectorpe', ['sector', 'date'], unique=True)
    op.create_index(op.f('ix_sectorpe_date'), 'sectorpe', ['date'], unique=False)
    op.create_index(op.f('ix_sectorpe_id'), 'sectorpe', ['id'], unique=False)
    op.create_index(op.f('ix_sectorpe_sector'), 'sectorpe', ['sector'], unique=False)
    op.create_table('sectorperformance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('average_change', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sector_perf_sector_date', 'sectorperformance', ['sector', 'date'], unique=True)
    op.create_index(op.f('ix_sectorperformance_date'), 'sectorperformance', ['date'], unique=False)
    op.create_index(op.f('ix_sectorperformance_id'), 'sectorperformance', ['id'], unique=False)
    op.create_index(op.f('ix_sectorperformance_sector'), 'sectorperformance', ['sector'], unique=False)
    op.create_table('sharesfloat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('free_float', sa.Float(), nullable=True),
    sa.Column('float_shares', sa.Float(), nullable=True),
    sa.Column('outstanding_shares', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_shares_float_symbol_date', 'sharesfloat', ['symbol', 'date'], unique=False)
    op.create_index(op.f('ix_sharesfloat_date'), 'sharesfloat', ['date'], unique=False)
    op.create_index(op.f('ix_sharesfloat_id'), 'sharesfloat', ['id'], unique=False)
    op.create_index(op.f('ix_sharesfloat_symbol'), 'sharesfloat', ['symbol'], unique=False)
    op.create_table('stockgainer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('changes_percentage', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gainer_date_symbol', 'stockgainer', ['date', 'symbol'], unique=False)
    op.create_index(op.f('ix_stockgainer_date'), 'stockgainer', ['date'], unique=False)
    op.create_index(op.f('ix_stockgainer_id'), 'stockgainer', ['id'], unique=False)
    op.create_index(op.f('ix_stockgainer_symbol'), 'stockgainer', ['symbol'], unique=False)
    op.create_table('stockloser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('changes_percentage', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_loser_date_symbol', 'stockloser', ['date', 'symbol'], unique=False)
    op.create_index(op.f('ix_stockloser_date'), 'stockloser', ['date'], unique=False)
    op.create_index(op.f('ix_stockloser_id'), 'stockloser', ['id'], unique=False)
    op.create_index(op.f('ix_stockloser_symbol'), 'stockloser', ['symbol'], unique=False)
    op.create_table('stocksymbol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('exchange_short_name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocksymbol_exchange_short_name'), 'stocksymbol', ['exchange_short_name'], unique=False)
    op.create_index(op.f('ix_stocksymbol_id'), 'stocksymbol', ['id'], unique=False)
    op.create_index(op.f('ix_stocksymbol_symbol'), 'stocksymbol', ['symbol'], unique=True)
    op.create_table('symbolchange',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('old_symbol', sa.String(), nullable=False),
    sa.Column('new_symbol', sa.String(), nullable=False),
    sa.Column('change_date', sa.String(), nullable=False),
    sa.Column('change_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_symbol_change_old_new', 'symbolchange', ['old_symbol', 'new_symbol'], unique=False)
    op.create_index(op.f('ix_symbolchange_change_date'), 'symbolchange', ['change_date'], unique=False)
    op.create_index(op.f('ix_symbolchange_id'), 'symbolchange', ['id'], unique=False)
    op.create_index(op.f('ix_symbolchange_new_symbol'), 'symbolchange', ['new_symbol'], unique=False)
    op.create_index(op.f('ix_symbolchange_old_symbol'), 'symbolchange', ['old_symbol'], unique=False)
    op.create_table('treasuryrate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('month_1', sa.Float(), nullable=True),
    sa.Column('month_2', sa.Float(), nullable=True),
    sa.Column('month_3', sa.Float(), nullable=True),
    sa.Column('month_6', sa.Float(), nullable=True),
    sa.Column('year_1', sa.Float(), nullable=True),
    sa.Column('year_2', sa.Float(), nullable=True),
    sa.Column('year_3', sa.Float(), nullable=True),
    sa.Column('year_5', sa.Float(), nullable=True),
    sa.Column('year_7', sa.Float(), nullable=True),
    sa.Column('year_10', sa.Float(), nullable=True),
    sa.Column('year_20', sa.Float(), nullable=True),
    sa.Column('year_30', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treasuryrate_date'), 'treasuryrate', ['date'], unique=True)
    op.create_index(op.f('ix_treasuryrate_id'), 'treasuryrate', ['id'], unique=False)
    op.drop_index('ix_company_id', table_name='company')
    op.drop_index('ix_company_ticker', table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sector', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='company_pkey')
    )
    op.create_index('ix_company_ticker', 'company', ['ticker'], unique=True)
    op.create_index('ix_company_id', 'company', ['id'], unique=False)
    op.drop_index(op.f('ix_treasuryrate_id'), table_name='treasuryrate')
    op.drop_index(op.f('ix_treasuryrate_date'), table_name='treasuryrate')
    op.drop_table('treasuryrate')
    op.drop_index(op.f('ix_symbolchange_old_symbol'), table_name='symbolchange')
    op.drop_index(op.f('ix_symbolchange_new_symbol'), table_name='symbolchange')
    op.drop_index(op.f('ix_symbolchange_id'), table_name='symbolchange')
    op.drop_index(op.f('ix_symbolchange_change_date'), table_name='symbolchange')
    op.drop_index('idx_symbol_change_old_new', table_name='symbolchange')
    op.drop_table('symbolchange')
    op.drop_index(op.f('ix_stocksymbol_symbol'), table_name='stocksymbol')
    op.drop_index(op.f('ix_stocksymbol_id'), table_name='stocksymbol')
    op.drop_index(op.f('ix_stocksymbol_exchange_short_name'), table_name='stocksymbol')
    op.drop_table('stocksymbol')
    op.drop_index(op.f('ix_stockloser_symbol'), table_name='stockloser')
    op.drop_index(op.f('ix_stockloser_id'), table_name='stockloser')
    op.drop_index(op.f('ix_stockloser_date'), table_name='stockloser')
    op.drop_index('idx_loser_date_symbol', table_name='stockloser')
    op.drop_table('stockloser')
    op.drop_index(op.f('ix_stockgainer_symbol'), table_name='stockgainer')
    op.drop_index(op.f('ix_stockgainer_id'), table_name='stockgainer')
    op.drop_index(op.f('ix_stockgainer_date'), table_name='stockgainer')
    op.drop_index('idx_gainer_date_symbol', table_name='stockgainer')
    op.drop_table('stockgainer')
    op.drop_index(op.f('ix_sharesfloat_symbol'), table_name='sharesfloat')
    op.drop_index(op.f('ix_sharesfloat_id'), table_name='sharesfloat')
    op.drop_index(op.f('ix_sharesfloat_date'), table_name='sharesfloat')
    op.drop_index('idx_shares_float_symbol_date', table_name='sharesfloat')
    op.drop_table('sharesfloat')
    op.drop_index(op.f('ix_sectorperformance_sector'), table_name='sectorperformance')
    op.drop_index(op.f('ix_sectorperformance_id'), table_name='sectorperformance')
    op.drop_index(op.f('ix_sectorperformance_date'), table_name='sectorperformance')
    op.drop_index('idx_sector_perf_sector_date', table_name='sectorperformance')
    op.drop_table('sectorperformance')
    op.drop_index(op.f('ix_sectorpe_sector'), table_name='sectorpe')
    op.drop_index(op.f('ix_sectorpe_id'), table_name='sectorpe')
    op.drop_index(op.f('ix_sectorpe_date'), table_name='sectorpe')
    op.drop_index('idx_sector_pe_sector_date', table_name='sectorpe')
    op.drop_table('sectorpe')
    op.drop_index(op.f('ix_sector_id'), table_name='sector')
    op.drop_table('sector')
    op.drop_index(op.f('ix_secfiling_symbol'), table_name='secfiling')
    op.drop_index(op.f('ix_secfiling_id'), table_name='secfiling')
    op.drop_index(op.f('ix_secfiling_form_type'), table_name='secfiling')
    op.drop_index(op.f('ix_secfiling_filing_date'), table_name='secfiling')
    op.drop_index(op.f('ix_secfiling_cik'), table_name='secfiling')
    op.drop_index('idx_sec_filing_symbol_date', table_name='secfiling')
    op.drop_index('idx_sec_filing_form_type', table_name='secfiling')
    op.drop_index('idx_sec_filing_cik_date', table_name='secfiling')
    op.drop_table('secfiling')
    op.drop_index(op.f('ix_quote_symbol'), table_name='quote')
    op.drop_index(op.f('ix_quote_id'), table_name='quote')
    op.drop_index('idx_quote_symbol_timestamp', table_name='quote')
    op.drop_table('quote')
    op.drop_index(op.f('ix_marketriskpremium_id'), table_name='marketriskpremium')
    op.drop_index(op.f('ix_marketriskpremium_continent'), table_name='marketriskpremium')
    op.drop_table('marketriskpremium')
    op.drop_index(op.f('ix_marketcapitalization_symbol'), table_name='marketcapitalization')
    op.drop_index(op.f('ix_marketcapitalization_id'), table_name='marketcapitalization')
    op.drop_index(op.f('ix_marketcapitalization_date'), table_name='marketcapitalization')
    op.drop_index('idx_market_cap_symbol_date', table_name='marketcapitalization')
    op.drop_table('marketcapitalization')
    op.drop_index(op.f('ix_intradayprice_symbol'), table_name='intradayprice')
    op.drop_index(op.f('ix_intradayprice_id'), table_name='intradayprice')
    op.drop_index(op.f('ix_intradayprice_date'), table_name='intradayprice')
    op.drop_index('idx_intraday_price_symbol_date', table_name='intradayprice')
    op.drop_table('intradayprice')
    op.drop_index(op.f('ix_industryperformance_industry'), table_name='industryperformance')
    op.drop_index(op.f('ix_industryperformance_id'), table_name='industryperformance')
    op.drop_index(op.f('ix_industryperformance_date'), table_name='industryperformance')
    op.drop_index('idx_industry_perf_industry_date', table_name='industryperformance')
    op.drop_table('industryperformance')
    op.drop_index(op.f('ix_industrype_industry'), table_name='industrype')
    op.drop_index(op.f('ix_industrype_id'), table_name='industrype')
    op.drop_index(op.f('ix_industrype_date'), table_name='industrype')
    op.drop_index('idx_industry_pe_industry_date', table_name='industrype')
    op.drop_table('industrype')
    op.drop_index(op.f('ix_industry_id'), table_name='industry')
    op.drop_table('industry')
    op.drop_index(op.f('ix_incomestatement_symbol'), table_name='incomestatement')
    op.drop_index(op.f('ix_incomestatement_period'), table_name='incomestatement')
    op.drop_index(op.f('ix_incomestatement_id'), table_name='incomestatement')
    op.drop_index(op.f('ix_incomestatement_date'), table_name='incomestatement')
    op.drop_index(op.f('ix_incomestatement_calendar_year'), table_name='incomestatement')
    op.drop_index('idx_income_stmt_symbol_period', table_name='incomestatement')
    op.drop_index('idx_income_stmt_symbol_date', table_name='incomestatement')
    op.drop_table('incomestatement')
    op.drop_index(op.f('ix_historicalprice_symbol'), table_name='historicalprice')
    op.drop_index(op.f('ix_historicalprice_id'), table_name='historicalprice')
    op.drop_index(op.f('ix_historicalprice_date'), table_name='historicalprice')
    op.drop_index('idx_historical_price_symbol_date', table_name='historicalprice')
    op.drop_table('historicalprice')
    op.drop_index(op.f('ix_executive_symbol'), table_name='executive')
    op.drop_index(op.f('ix_executive_id'), table_name='executive')
    op.drop_index('idx_executive_symbol_name', table_name='executive')
    op.drop_table('executive')
    op.drop_index(op.f('ix_exchange_id'), table_name='exchange')
    op.drop_index(op.f('ix_exchange_country'), table_name='exchange')
    op.drop_table('exchange')
    op.drop_index(op.f('ix_employeecount_symbol'), table_name='employeecount')
    op.drop_index(op.f('ix_employeecount_id'), table_name='employeecount')
    op.drop_index(op.f('ix_employeecount_filing_date'), table_name='employeecount')
    op.drop_index('idx_employee_symbol_date', table_name='employeecount')
    op.drop_table('employeecount')
    op.drop_index(op.f('ix_economicindicator_name'), table_name='economicindicator')
    op.drop_index(op.f('ix_economicindicator_id'), table_name='economicindicator')
    op.drop_index(op.f('ix_economicindicator_date'), table_name='economicindicator')
    op.drop_index(op.f('ix_economicindicator_country'), table_name='economicindicator')
    op.drop_index('idx_econ_indicator_name_date', table_name='economicindicator')
    op.drop_index('idx_econ_indicator_country_name', table_name='economicindicator')
    op.drop_table('economicindicator')
    op.drop_index(op.f('ix_economiccalendarevent_id'), table_name='economiccalendarevent')
    op.drop_index(op.f('ix_economiccalendarevent_event'), table_name='economiccalendarevent')
    op.drop_index(op.f('ix_economiccalendarevent_date'), table_name='economiccalendarevent')
    op.drop_index(op.f('ix_economiccalendarevent_country'), table_name='economiccalendarevent')
    op.drop_index('idx_econ_cal_event', table_name='economiccalendarevent')
    op.drop_index('idx_econ_cal_date_country', table_name='economiccalendarevent')
    op.drop_table('economiccalendarevent')
    op.drop_index(op.f('ix_earningsreport_symbol'), table_name='earningsreport')
    op.drop_index(op.f('ix_earningsreport_period'), table_name='earningsreport')
    op.drop_index(op.f('ix_earningsreport_id'), table_name='earningsreport')
    op.drop_index(op.f('ix_earningsreport_date'), table_name='earningsreport')
    op.drop_index('idx_earnings_symbol_period', table_name='earningsreport')
    op.drop_index('idx_earnings_symbol_date', table_name='earningsreport')
    op.drop_table('earningsreport')
    op.drop_index(op.f('ix_earningscalendarevent_symbol'), table_name='earningscalendarevent')
    op.drop_index(op.f('ix_earningscalendarevent_id'), table_name='earningscalendarevent')
    op.drop_index(op.f('ix_earningscalendarevent_date'), table_name='earningscalendarevent')
    op.drop_index('idx_earnings_cal_symbol_date', table_name='earningscalendarevent')
    op.drop_table('earningscalendarevent')
    op.drop_index(op.f('ix_dividendcalendarevent_symbol'), table_name='dividendcalendarevent')
    op.drop_index(op.f('ix_dividendcalendarevent_id'), table_name='dividendcalendarevent')
    op.drop_index(op.f('ix_dividendcalendarevent_date'), table_name='dividendcalendarevent')
    op.drop_index('idx_div_calendar_symbol_date', table_name='dividendcalendarevent')
    op.drop_table('dividendcalendarevent')
    op.drop_index(op.f('ix_dividend_symbol'), table_name='dividend')
    op.drop_index(op.f('ix_dividend_id'), table_name='dividend')
    op.drop_index(op.f('ix_dividend_date'), table_name='dividend')
    op.drop_index('idx_dividend_symbol_date', table_name='dividend')
    op.drop_table('dividend')
    op.drop_index(op.f('ix_delistedcompany_symbol'), table_name='delistedcompany')
    op.drop_index(op.f('ix_delistedcompany_id'), table_name='delistedcompany')
    op.drop_index(op.f('ix_delistedcompany_delisted_date'), table_name='delistedcompany')
    op.drop_table('delistedcompany')
    op.drop_index(op.f('ix_country_id'), table_name='country')
    op.drop_table('country')
    op.drop_index(op.f('ix_companyprofile_symbol'), table_name='companyprofile')
    op.drop_index(op.f('ix_companyprofile_sector'), table_name='companyprofile')
    op.drop_index(op.f('ix_companyprofile_industry'), table_name='companyprofile')
    op.drop_index(op.f('ix_companyprofile_id'), table_name='companyprofile')
    op.drop_index(op.f('ix_companyprofile_country'), table_name='companyprofile')
    op.drop_index(op.f('ix_companyprofile_cik'), table_name='companyprofile')
    op.drop_index('idx_company_sector_industry', table_name='companyprofile')
    op.drop_index('idx_company_country_exchange', table_name='companyprofile')
    op.drop_table('companyprofile')
    op.drop_index(op.f('ix_cashflowstatement_symbol'), table_name='cashflowstatement')
    op.drop_index(op.f('ix_cashflowstatement_period'), table_name='cashflowstatement')
    op.drop_index(op.f('ix_cashflowstatement_id'), table_name='cashflowstatement')
    op.drop_index(op.f('ix_cashflowstatement_date'), table_name='cashflowstatement')
    op.drop_index(op.f('ix_cashflowstatement_calendar_year'), table_name='cashflowstatement')
    op.drop_index('idx_cash_flow_symbol_period', table_name='cashflowstatement')
    op.drop_index('idx_cash_flow_symbol_date', table_name='cashflowstatement')
    op.drop_table('cashflowstatement')
    op.drop_index(op.f('ix_balancesheet_symbol'), table_name='balancesheet')
    op.drop_index(op.f('ix_balancesheet_period'), table_name='balancesheet')
    op.drop_index(op.f('ix_balancesheet_id'), table_name='balancesheet')
    op.drop_index(op.f('ix_balancesheet_date'), table_name='balancesheet')
    op.drop_index(op.f('ix_balancesheet_calendar_year'), table_name='balancesheet')
    op.drop_index('idx_balance_sheet_symbol_period', table_name='balancesheet')
    op.drop_index('idx_balance_sheet_symbol_date', table_name='balancesheet')
    op.drop_table('balancesheet')
    op.drop_index(op.f('ix_activestock_symbol'), table_name='activestock')
    op.drop_index(op.f('ix_activestock_id'), table_name='activestock')
    op.drop_index(op.f('ix_activestock_date'), table_name='activestock')
    op.drop_index('idx_active_date_symbol', table_name='activestock')
    op.drop_table('activestock')
    # ### end Alembic commands ###
