"""Make quote symbol_timestamp index unique

Revision ID: 44efcfd777b8
Revises: 620425ab82b6
Create Date: 2026-01-18 17:40:00.013585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44efcfd777b8'
down_revision = '620425ab82b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_quote_symbol_timestamp'), table_name='quote')
    op.create_index('idx_quote_symbol_timestamp', 'quote', ['symbol', 'timestamp'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_quote_symbol_timestamp', table_name='quote')
    op.create_index(op.f('idx_quote_symbol_timestamp'), 'quote', ['symbol', 'timestamp'], unique=False)
    # ### end Alembic commands ###
