"""Change EconomicCalendarEvent date from string to date

Revision ID: 51e63c9c0d65
Revises: ba14749a0159
Create Date: 2026-01-10 15:44:13.800643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51e63c9c0d65'
down_revision = 'ba14749a0159'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the unique index first to allow type conversion
    op.drop_index('idx_econ_cal_date_event_country', table_name='economiccalendarevent')

    # Convert the column type first
    op.alter_column('economiccalendarevent', 'date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using='date::date')

    # Remove duplicates after type conversion, before adding unique constraint
    # Keep only the row with the highest id for each (date, event, country) combo
    op.execute("""
        DELETE FROM economiccalendarevent a
        USING economiccalendarevent b
        WHERE a.id < b.id
          AND a.date = b.date
          AND a.event IS NOT DISTINCT FROM b.event
          AND a.country IS NOT DISTINCT FROM b.country
    """)

    # Recreate the unique index
    op.create_index('idx_econ_cal_date_event_country', 'economiccalendarevent',
                    ['date', 'event', 'country'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('economiccalendarevent', 'date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
