"""Add company_metrics table2

Revision ID: 620425ab82b6
Revises: cc6360836fc6
Create Date: 2026-01-17 17:38:37.016258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '620425ab82b6'
down_revision = 'cc6360836fc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companymetrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('dividend_growth_10y', sa.Float(), nullable=True),
    sa.Column('years_increasing_dividend', sa.Integer(), nullable=True),
    sa.Column('copm', sa.Float(), nullable=True),
    sa.Column('roic', sa.Float(), nullable=True),
    sa.Column('rota', sa.Float(), nullable=True),
    sa.Column('debt_ebitda_ratio', sa.Float(), nullable=True),
    sa.Column('ev_ebitda_ratio', sa.Float(), nullable=True),
    sa.Column('ev_fcf_ration', sa.Float(), nullable=True),
    sa.Column('pb_ratio', sa.Float(), nullable=True),
    sa.Column('ps_ratio', sa.Float(), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('dividend_payout', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_company_metrics_symbol', 'companymetrics', ['symbol'], unique=True)
    op.create_index(op.f('ix_companymetrics_id'), 'companymetrics', ['id'], unique=False)
    op.create_index(op.f('ix_companymetrics_symbol'), 'companymetrics', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companymetrics_symbol'), table_name='companymetrics')
    op.drop_index(op.f('ix_companymetrics_id'), table_name='companymetrics')
    op.drop_index('idx_company_metrics_symbol', table_name='companymetrics')
    op.drop_table('companymetrics')
    # ### end Alembic commands ###
