"""Update fields in StockSymbol

Revision ID: 82d16e216c47
Revises: ca11bd909394
Create Date: 2026-01-07 21:29:14.867629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82d16e216c47'
down_revision = 'ca11bd909394'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocksymbol', sa.Column('currency', sa.String(), nullable=True))
    op.drop_column('stocksymbol', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocksymbol', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('stocksymbol', 'currency')
    # ### end Alembic commands ###
