"""Add unique constraint to economic_calendar_event index

Revision ID: 83a7bd2eea7d
Revises: cd2a9b65fc00
Create Date: 2026-01-10 15:34:39.135888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83a7bd2eea7d'
down_revision = 'cd2a9b65fc00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_econ_cal_date_country', table_name='economiccalendarevent')
    op.drop_index('idx_econ_cal_event', table_name='economiccalendarevent')
    op.create_index('idx_econ_cal_date_event_country', 'economiccalendarevent', ['date', 'event', 'country'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_econ_cal_date_event_country', table_name='economiccalendarevent')
    op.create_index('idx_econ_cal_event', 'economiccalendarevent', ['event'], unique=False)
    op.create_index('idx_econ_cal_date_country', 'economiccalendarevent', ['date', 'country'], unique=False)
    # ### end Alembic commands ###
