"""Add unique constraint to EarningsCalendarEvent

Revision ID: 898485f13588
Revises: 9b4ce49be5a6
Create Date: 2026-01-10 16:15:50.651555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898485f13588'
down_revision = '9b4ce49be5a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop existing non-unique index
    op.drop_index('idx_earnings_cal_symbol_date', table_name='earningscalendarevent')

    # Delete duplicates before creating unique index (keep the one with highest id)
    op.execute("""
        DELETE FROM earningscalendarevent a
        USING earningscalendarevent b
        WHERE a.id < b.id
        AND a.symbol = b.symbol
        AND a.date = b.date
    """)

    # Create unique index
    op.create_index('idx_earnings_cal_symbol_date', 'earningscalendarevent', ['symbol', 'date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_earnings_cal_symbol_date', table_name='earningscalendarevent')
    op.create_index('idx_earnings_cal_symbol_date', 'earningscalendarevent', ['symbol', 'date'], unique=False)
    # ### end Alembic commands ###
