"""Rename ev_fcf_ratio column in company metrics

Revision ID: 908032d39437
Revises: 44efcfd777b8
Create Date: 2026-01-18 20:05:15.481880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '908032d39437'
down_revision = '44efcfd777b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companymetrics', sa.Column('ev_fcf_ratio', sa.Float(), nullable=True))
    op.drop_column('companymetrics', 'ev_fcf_ration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companymetrics', sa.Column('ev_fcf_ration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('companymetrics', 'ev_fcf_ratio')
    # ### end Alembic commands ###
