"""Convert all date string fields to Date type

Revision ID: 9b4ce49be5a6
Revises: 51e63c9c0d65
Create Date: 2026-01-10 15:58:17.698485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b4ce49be5a6'
down_revision = '51e63c9c0d65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use NULLIF to convert empty strings to NULL before casting to date/timestamp
    op.alter_column('activestock', 'date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using='NULLIF(date, \'\')::date')
    op.alter_column('balancesheet', 'date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using='NULLIF(date, \'\')::date')
    op.alter_column('balancesheet', 'filling_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='NULLIF(filling_date, \'\')::date')
    op.alter_column('balancesheet', 'accepted_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='NULLIF(accepted_date, \'\')::date')
    op.alter_column('cashflowstatement', 'date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using='NULLIF(date, \'\')::date')
    op.alter_column('cashflowstatement', 'filling_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='NULLIF(filling_date, \'\')::date')
    op.alter_column('cashflowstatement', 'accepted_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='NULLIF(accepted_date, \'\')::date')
    op.alter_column('companyprofile', 'ipo_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='NULLIF(ipo_date, \'\')::date')
    op.alter_column('delistedcompany', 'ipo_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='NULLIF(ipo_date, \'\')::date')
    op.alter_column('delistedcompany', 'delisted_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='NULLIF(delisted_date, \'\')::date')
    op.alter_column('dividend', 'date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using='NULLIF(date, \'\')::date')
    op.alter_column('dividend', 'record_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='NULLIF(record_date, \'\')::date')
    op.alter_column('dividend', 'payment_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='NULLIF(payment_date, \'\')::date')
    op.alter_column('dividend', 'declaration_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='NULLIF(declaration_date, \'\')::date')
    op.alter_column('dividendcalendarevent', 'record_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='NULLIF(record_date, \'\')::date')
    op.alter_column('dividendcalendarevent', 'payment_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='NULLIF(payment_date, \'\')::date')
    op.alter_column('dividendcalendarevent', 'declaration_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='NULLIF(declaration_date, \'\')::date')
    op.alter_column('earningscalendarevent', 'date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using='NULLIF(date, \'\')::date')
    op.alter_column('earningsreport', 'date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using='NULLIF(date, \'\')::date')
    op.alter_column('employeecount', 'filing_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='NULLIF(filing_date, \'\')::date')
    op.alter_column('historicalprice', 'date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using='NULLIF(date, \'\')::date')
    op.alter_column('incomestatement', 'date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using='NULLIF(date, \'\')::date')
    op.alter_column('incomestatement', 'filling_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='NULLIF(filling_date, \'\')::date')
    op.alter_column('incomestatement', 'accepted_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='NULLIF(accepted_date, \'\')::date')
    op.alter_column('industrype', 'date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using='NULLIF(date, \'\')::date')
    op.alter_column('industryperformance', 'date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using='NULLIF(date, \'\')::date')
    op.alter_column('intradayprice', 'date',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=False,
               postgresql_using='NULLIF(date, \'\')::timestamp')
    op.alter_column('marketcapitalization', 'date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using='NULLIF(date, \'\')::date')
    op.alter_column('secfiling', 'accepted_date',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True,
               postgresql_using='NULLIF(accepted_date, \'\')::timestamp')
    op.alter_column('secfiling', 'filing_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using='NULLIF(filing_date, \'\')::date')
    op.alter_column('sectorpe', 'date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using='NULLIF(date, \'\')::date')
    op.alter_column('sectorperformance', 'date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using='NULLIF(date, \'\')::date')
    op.alter_column('sharesfloat', 'date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='NULLIF(date, \'\')::date')
    op.alter_column('stockgainer', 'date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using='NULLIF(date, \'\')::date')
    op.alter_column('stockloser', 'date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using='NULLIF(date, \'\')::date')
    op.alter_column('symbolchange', 'change_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using='NULLIF(change_date, \'\')::date')
    op.alter_column('treasuryrate', 'date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using='NULLIF(date, \'\')::date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('treasuryrate', 'date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('symbolchange', 'change_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('stockloser', 'date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('stockgainer', 'date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('sharesfloat', 'date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('sectorperformance', 'date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('sectorpe', 'date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('secfiling', 'filing_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('secfiling', 'accepted_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('marketcapitalization', 'date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('intradayprice', 'date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('industryperformance', 'date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('industrype', 'date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('incomestatement', 'accepted_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('incomestatement', 'filling_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('incomestatement', 'date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('historicalprice', 'date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('employeecount', 'filing_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('earningsreport', 'date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('earningscalendarevent', 'date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('dividendcalendarevent', 'declaration_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('dividendcalendarevent', 'payment_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('dividendcalendarevent', 'record_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('dividend', 'declaration_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('dividend', 'payment_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('dividend', 'record_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('dividend', 'date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('delistedcompany', 'delisted_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('delistedcompany', 'ipo_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('companyprofile', 'ipo_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('cashflowstatement', 'accepted_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('cashflowstatement', 'filling_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('cashflowstatement', 'date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('balancesheet', 'accepted_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('balancesheet', 'filling_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('balancesheet', 'date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('activestock', 'date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
