"""change_stock_symbol_primary_key

Revision ID: ca11bd909394
Revises: 43a939f4a0b6
Create Date: 2026-01-07 19:13:05.556294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca11bd909394'
down_revision = '43a939f4a0b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stocksymbol', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_stocksymbol_id', table_name='stocksymbol')
    op.drop_index('ix_stocksymbol_symbol', table_name='stocksymbol')
    # Drop the existing primary key constraint
    op.drop_constraint('stocksymbol_pkey', 'stocksymbol', type_='primary')
    # Drop the id column
    op.drop_column('stocksymbol', 'id')
    # Add primary key constraint to symbol column
    op.create_primary_key('stocksymbol_pkey', 'stocksymbol', ['symbol'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the primary key constraint on symbol
    op.drop_constraint('stocksymbol_pkey', 'stocksymbol', type_='primary')
    # Add back the id column
    op.add_column('stocksymbol', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    # Create primary key constraint on id column
    op.create_primary_key('stocksymbol_pkey', 'stocksymbol', ['id'])
    # Recreate indexes
    op.create_index('ix_stocksymbol_symbol', 'stocksymbol', ['symbol'], unique=True)
    op.create_index('ix_stocksymbol_id', 'stocksymbol', ['id'], unique=False)
    op.alter_column('stocksymbol', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
