"""Add unique constraint to economic_indicator index

Revision ID: cd2a9b65fc00
Revises: ed9e74c76ec9
Create Date: 2026-01-10 08:35:54.426235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd2a9b65fc00'
down_revision = 'ed9e74c76ec9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_econ_indicator_country_name', table_name='economicindicator')
    op.drop_index('idx_econ_indicator_name_date', table_name='economicindicator')
    op.create_index('idx_econ_indicator_name_date_country', 'economicindicator', ['name', 'date', 'country'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_econ_indicator_name_date_country', table_name='economicindicator')
    op.create_index('idx_econ_indicator_name_date', 'economicindicator', ['name', 'date'], unique=False)
    op.create_index('idx_econ_indicator_country_name', 'economicindicator', ['country', 'name'], unique=False)
    # ### end Alembic commands ###
