"""Add unique constraint to dividend_calendar_event index

Revision ID: ed9e74c76ec9
Revises: f68e883e9f71
Create Date: 2026-01-10 08:20:59.179734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed9e74c76ec9'
down_revision = 'f68e883e9f71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_div_calendar_symbol_date', table_name='dividendcalendarevent')
    op.create_index('idx_div_calendar_symbol_date', 'dividendcalendarevent', ['symbol', 'date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_div_calendar_symbol_date', table_name='dividendcalendarevent')
    op.create_index('idx_div_calendar_symbol_date', 'dividendcalendarevent', ['symbol', 'date'], unique=False)
    # ### end Alembic commands ###
