"""add_financial_statement_symbol_table

Revision ID: f68e883e9f71
Revises: 82d16e216c47
Create Date: 2026-01-07 21:51:31.229520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f68e883e9f71'
down_revision = '82d16e216c47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financialstatementsymbol',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('trading_currency', sa.String(), nullable=True),
    sa.Column('reporting_currency', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financialstatementsymbol')
    # ### end Alembic commands ###
