"""Mappers for converting FMP client DTOs to database models - Financial statements."""

from fmpclient.models import financial as fmp_financial
from app.models.financial_statements import (
    IncomeStatement,
    BalanceSheet,
    CashFlowStatement,
)


def map_income_statement(dto: fmp_financial.IncomeStatement) -> IncomeStatement:
    """Convert FMP IncomeStatement DTO to database model."""
    return IncomeStatement(
        date=dto.date,
        symbol=dto.symbol,
        reported_currency=dto.reported_currency,
        cik=dto.cik,
        filling_date=dto.filling_date,
        accepted_date=dto.accepted_date,
        calendar_year=dto.calendar_year,
        period=dto.period,
        revenue=dto.revenue,
        cost_of_revenue=dto.cost_of_revenue,
        gross_profit=dto.gross_profit,
        gross_profit_ratio=dto.gross_profit_ratio,
        research_and_development_expenses=dto.research_and_development_expenses,
        general_and_administrative_expenses=dto.general_and_administrative_expenses,
        selling_and_marketing_expenses=dto.selling_and_marketing_expenses,
        selling_general_and_administrative_expenses=dto.selling_general_and_administrative_expenses,
        other_expenses=dto.other_expenses,
        operating_expenses=dto.operating_expenses,
        cost_and_expenses=dto.cost_and_expenses,
        interest_income=dto.interest_income,
        interest_expense=dto.interest_expense,
        depreciation_and_amortization=dto.depreciation_and_amortization,
        ebitda=dto.ebitda,
        ebitda_ratio=dto.ebitda_ratio,
        operating_income=dto.operating_income,
        operating_income_ratio=dto.operating_income_ratio,
        total_other_income_expenses_net=dto.total_other_income_expenses_net,
        income_before_tax=dto.income_before_tax,
        income_before_tax_ratio=dto.income_before_tax_ratio,
        income_tax_expense=dto.income_tax_expense,
        net_income=dto.net_income,
        net_income_ratio=dto.net_income_ratio,
        eps=dto.eps,
        eps_diluted=dto.eps_diluted,
        weighted_average_shs_out=dto.weighted_average_shs_out,
        weighted_average_shs_out_dil=dto.weighted_average_shs_out_dil,
        link=dto.link,
        final_link=dto.final_link,
    )


def map_balance_sheet(dto: fmp_financial.BalanceSheet) -> BalanceSheet:
    """Convert FMP BalanceSheet DTO to database model."""
    return BalanceSheet(
        date=dto.date,
        symbol=dto.symbol,
        reported_currency=dto.reported_currency,
        cik=dto.cik,
        filling_date=dto.filling_date,
        accepted_date=dto.accepted_date,
        calendar_year=dto.calendar_year,
        period=dto.period,
        cash_and_cash_equivalents=dto.cash_and_cash_equivalents,
        short_term_investments=dto.short_term_investments,
        cash_and_short_term_investments=dto.cash_and_short_term_investments,
        net_receivables=dto.net_receivables,
        inventory=dto.inventory,
        other_current_assets=dto.other_current_assets,
        total_current_assets=dto.total_current_assets,
        property_plant_equipment_net=dto.property_plant_equipment_net,
        goodwill=dto.goodwill,
        intangible_assets=dto.intangible_assets,
        goodwill_and_intangible_assets=dto.goodwill_and_intangible_assets,
        long_term_investments=dto.long_term_investments,
        tax_assets=dto.tax_assets,
        other_non_current_assets=dto.other_non_current_assets,
        total_non_current_assets=dto.total_non_current_assets,
        other_assets=dto.other_assets,
        total_assets=dto.total_assets,
        account_payables=dto.account_payables,
        short_term_debt=dto.short_term_debt,
        tax_payables=dto.tax_payables,
        deferred_revenue=dto.deferred_revenue,
        other_current_liabilities=dto.other_current_liabilities,
        total_current_liabilities=dto.total_current_liabilities,
        long_term_debt=dto.long_term_debt,
        deferred_revenue_non_current=dto.deferred_revenue_non_current,
        deferred_tax_liabilities_non_current=dto.deferred_tax_liabilities_non_current,
        other_non_current_liabilities=dto.other_non_current_liabilities,
        total_non_current_liabilities=dto.total_non_current_liabilities,
        other_liabilities=dto.other_liabilities,
        capital_lease_obligations=dto.capital_lease_obligations,
        total_liabilities=dto.total_liabilities,
        preferred_stock=dto.preferred_stock,
        common_stock=dto.common_stock,
        retained_earnings=dto.retained_earnings,
        accumulated_other_comprehensive_income_loss=dto.accumulated_other_comprehensive_income_loss,
        other_total_stockholders_equity=dto.other_total_stockholders_equity,
        total_stockholders_equity=dto.total_stockholders_equity,
        total_equity=dto.total_equity,
        total_liabilities_and_stockholders_equity=dto.total_liabilities_and_stockholders_equity,
        minority_interest=dto.minority_interest,
        total_liabilities_and_total_equity=dto.total_liabilities_and_total_equity,
        total_investments=dto.total_investments,
        total_debt=dto.total_debt,
        net_debt=dto.net_debt,
        link=dto.link,
        final_link=dto.final_link,
    )


def map_cash_flow_statement(dto: fmp_financial.CashFlowStatement) -> CashFlowStatement:
    """Convert FMP CashFlowStatement DTO to database model."""
    return CashFlowStatement(
        date=dto.date,
        symbol=dto.symbol,
        reported_currency=dto.reported_currency,
        cik=dto.cik,
        filling_date=dto.filling_date,
        accepted_date=dto.accepted_date,
        calendar_year=dto.calendar_year,
        period=dto.period,
        net_income=dto.net_income,
        depreciation_and_amortization=dto.depreciation_and_amortization,
        deferred_income_tax=dto.deferred_income_tax,
        stock_based_compensation=dto.stock_based_compensation,
        change_in_working_capital=dto.change_in_working_capital,
        accounts_receivables=dto.accounts_receivables,
        inventory=dto.inventory,
        accounts_payables=dto.accounts_payables,
        other_working_capital=dto.other_working_capital,
        other_non_cash_items=dto.other_non_cash_items,
        net_cash_provided_by_operating_activities=dto.net_cash_provided_by_operating_activities,
        investments_in_property_plant_and_equipment=dto.investments_in_property_plant_and_equipment,
        acquisitions_net=dto.acquisitions_net,
        purchases_of_investments=dto.purchases_of_investments,
        sales_maturities_of_investments=dto.sales_maturities_of_investments,
        other_investing_activities=dto.other_investing_activities,
        net_cash_used_for_investing_activities=dto.net_cash_used_for_investing_activities,
        debt_repayment=dto.debt_repayment,
        common_stock_issued=dto.common_stock_issued,
        common_stock_repurchased=dto.common_stock_repurchased,
        dividends_paid=dto.dividends_paid,
        other_financing_activities=dto.other_financing_activities,
        net_cash_used_provided_by_financing_activities=dto.net_cash_used_provided_by_financing_activities,
        effect_of_forex_changes_on_cash=dto.effect_of_forex_changes_on_cash,
        net_change_in_cash=dto.net_change_in_cash,
        cash_at_end_of_period=dto.cash_at_end_of_period,
        cash_at_beginning_of_period=dto.cash_at_beginning_of_period,
        operating_cash_flow=dto.operating_cash_flow,
        capital_expenditure=dto.capital_expenditure,
        free_cash_flow=dto.free_cash_flow,
        link=dto.link,
        final_link=dto.final_link,
    )
