from sqlalchemy import Column, Date, Integer, String, Float, DateTime, Index
from sqlalchemy.sql import func
from app.db.base_class import BaseModel


class IncomeStatement(BaseModel):
    """Income statement data."""

    id = Column(Integer, primary_key=True, index=True)
    date = Column(Date, index=True, nullable=False)
    symbol = Column(String, index=True, nullable=False)
    reported_currency = Column(String, nullable=True)
    cik = Column(String, nullable=True)
    filling_date = Column(Date, nullable=True)
    accepted_date = Column(Date, nullable=True)
    calendar_year = Column(String, index=True, nullable=True)
    period = Column(String, index=True, nullable=True)
    revenue = Column(Float, nullable=True)
    cost_of_revenue = Column(Float, nullable=True)
    gross_profit = Column(Float, nullable=True)
    gross_profit_ratio = Column(Float, nullable=True)
    research_and_development_expenses = Column(Float, nullable=True)
    general_and_administrative_expenses = Column(Float, nullable=True)
    selling_and_marketing_expenses = Column(Float, nullable=True)
    selling_general_and_administrative_expenses = Column(Float, nullable=True)
    other_expenses = Column(Float, nullable=True)
    operating_expenses = Column(Float, nullable=True)
    cost_and_expenses = Column(Float, nullable=True)
    interest_income = Column(Float, nullable=True)
    interest_expense = Column(Float, nullable=True)
    depreciation_and_amortization = Column(Float, nullable=True)
    ebitda = Column(Float, nullable=True)
    ebitda_ratio = Column(Float, nullable=True)
    operating_income = Column(Float, nullable=True)
    operating_income_ratio = Column(Float, nullable=True)
    total_other_income_expenses_net = Column(Float, nullable=True)
    income_before_tax = Column(Float, nullable=True)
    income_before_tax_ratio = Column(Float, nullable=True)
    income_tax_expense = Column(Float, nullable=True)
    net_income = Column(Float, nullable=True)
    net_income_ratio = Column(Float, nullable=True)
    eps = Column(Float, nullable=True)
    eps_diluted = Column(Float, nullable=True)
    weighted_average_shs_out = Column(Float, nullable=True)
    weighted_average_shs_out_dil = Column(Float, nullable=True)
    link = Column(String, nullable=True)
    final_link = Column(String, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    __table_args__ = (
        Index('idx_income_stmt_symbol_date', 'symbol', 'date', unique=True),
        Index('idx_income_stmt_symbol_period', 'symbol', 'calendar_year', 'period'),
    )


class BalanceSheet(BaseModel):
    """Balance sheet data."""

    id = Column(Integer, primary_key=True, index=True)
    date = Column(Date, index=True, nullable=False)
    symbol = Column(String, index=True, nullable=False)
    reported_currency = Column(String, nullable=True)
    cik = Column(String, nullable=True)
    filling_date = Column(Date, nullable=True)
    accepted_date = Column(Date, nullable=True)
    calendar_year = Column(String, index=True, nullable=True)
    period = Column(String, index=True, nullable=True)
    cash_and_cash_equivalents = Column(Float, nullable=True)
    short_term_investments = Column(Float, nullable=True)
    cash_and_short_term_investments = Column(Float, nullable=True)
    net_receivables = Column(Float, nullable=True)
    inventory = Column(Float, nullable=True)
    other_current_assets = Column(Float, nullable=True)
    total_current_assets = Column(Float, nullable=True)
    property_plant_equipment_net = Column(Float, nullable=True)
    goodwill = Column(Float, nullable=True)
    intangible_assets = Column(Float, nullable=True)
    goodwill_and_intangible_assets = Column(Float, nullable=True)
    long_term_investments = Column(Float, nullable=True)
    tax_assets = Column(Float, nullable=True)
    other_non_current_assets = Column(Float, nullable=True)
    total_non_current_assets = Column(Float, nullable=True)
    other_assets = Column(Float, nullable=True)
    total_assets = Column(Float, nullable=True)
    account_payables = Column(Float, nullable=True)
    short_term_debt = Column(Float, nullable=True)
    tax_payables = Column(Float, nullable=True)
    deferred_revenue = Column(Float, nullable=True)
    other_current_liabilities = Column(Float, nullable=True)
    total_current_liabilities = Column(Float, nullable=True)
    long_term_debt = Column(Float, nullable=True)
    deferred_revenue_non_current = Column(Float, nullable=True)
    deferred_tax_liabilities_non_current = Column(Float, nullable=True)
    other_non_current_liabilities = Column(Float, nullable=True)
    total_non_current_liabilities = Column(Float, nullable=True)
    other_liabilities = Column(Float, nullable=True)
    capital_lease_obligations = Column(Float, nullable=True)
    total_liabilities = Column(Float, nullable=True)
    preferred_stock = Column(Float, nullable=True)
    common_stock = Column(Float, nullable=True)
    retained_earnings = Column(Float, nullable=True)
    accumulated_other_comprehensive_income_loss = Column(Float, nullable=True)
    other_total_stockholders_equity = Column(Float, nullable=True)
    total_stockholders_equity = Column(Float, nullable=True)
    total_equity = Column(Float, nullable=True)
    total_liabilities_and_stockholders_equity = Column(Float, nullable=True)
    minority_interest = Column(Float, nullable=True)
    total_liabilities_and_total_equity = Column(Float, nullable=True)
    total_investments = Column(Float, nullable=True)
    total_debt = Column(Float, nullable=True)
    net_debt = Column(Float, nullable=True)
    link = Column(String, nullable=True)
    final_link = Column(String, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    __table_args__ = (
        Index('idx_balance_sheet_symbol_date', 'symbol', 'date', unique=True),
        Index('idx_balance_sheet_symbol_period', 'symbol', 'calendar_year', 'period'),
    )


class CashFlowStatement(BaseModel):
    """Cash flow statement data."""

    id = Column(Integer, primary_key=True, index=True)
    date = Column(Date, index=True, nullable=False)
    symbol = Column(String, index=True, nullable=False)
    reported_currency = Column(String, nullable=True)
    cik = Column(String, nullable=True)
    filling_date = Column(Date, nullable=True)
    accepted_date = Column(Date, nullable=True)
    calendar_year = Column(String, index=True, nullable=True)
    period = Column(String, index=True, nullable=True)
    net_income = Column(Float, nullable=True)
    depreciation_and_amortization = Column(Float, nullable=True)
    deferred_income_tax = Column(Float, nullable=True)
    stock_based_compensation = Column(Float, nullable=True)
    change_in_working_capital = Column(Float, nullable=True)
    accounts_receivables = Column(Float, nullable=True)
    inventory = Column(Float, nullable=True)
    accounts_payables = Column(Float, nullable=True)
    other_working_capital = Column(Float, nullable=True)
    other_non_cash_items = Column(Float, nullable=True)
    net_cash_provided_by_operating_activities = Column(Float, nullable=True)
    investments_in_property_plant_and_equipment = Column(Float, nullable=True)
    acquisitions_net = Column(Float, nullable=True)
    purchases_of_investments = Column(Float, nullable=True)
    sales_maturities_of_investments = Column(Float, nullable=True)
    other_investing_activities = Column(Float, nullable=True)
    net_cash_used_for_investing_activities = Column(Float, nullable=True)
    debt_repayment = Column(Float, nullable=True)
    common_stock_issued = Column(Float, nullable=True)
    common_stock_repurchased = Column(Float, nullable=True)
    dividends_paid = Column(Float, nullable=True)
    other_financing_activities = Column(Float, nullable=True)
    net_cash_used_provided_by_financing_activities = Column(Float, nullable=True)
    effect_of_forex_changes_on_cash = Column(Float, nullable=True)
    net_change_in_cash = Column(Float, nullable=True)
    cash_at_end_of_period = Column(Float, nullable=True)
    cash_at_beginning_of_period = Column(Float, nullable=True)
    operating_cash_flow = Column(Float, nullable=True)
    capital_expenditure = Column(Float, nullable=True)
    free_cash_flow = Column(Float, nullable=True)
    link = Column(String, nullable=True)
    final_link = Column(String, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    __table_args__ = (
        Index('idx_cash_flow_symbol_date', 'symbol', 'date', unique=True),
        Index('idx_cash_flow_symbol_period', 'symbol', 'calendar_year', 'period'),
    )
